config-working: true
events:
    join:
        - "[Message] welcome"
        - "[Give]" :
            type: STONE
            amount: 4
        - "[Message] second message"
        - "[ForceChat] I am forced to chat."
        - "{KillPlayer}"
actions:
   KillPlayer:
        - '[Kill]'
        - '[Message] You died by mistycal powers.'