#Welcome to ActionLib's config
#More info at https://www.spigotmc.org/wiki/actionlib/
#Developed by SrAldeano (MarkelM16)
events:
#   These actions will be fired when some of the event occur
#   You can use the following events: join, kill, fish, first-join, tame, chat, first-join, leave, death, teleport and pickup.
    join:
        - '[Message] Welcome again %player% to the server!'
        - '[Give]' :
            type: STONE
            amount: 4
    kill:
        - '[VaultGive] 30'
    fish:
        - '[Broadcast] &6%player% caught a fish!'
    first-join:
        - '{Welcome}'

actions:
#  Here you can create action-packs
#  Then you can send them using {YourPack}. *Names can be custom but not repeated
   KillPlayer:
        - '[Kill]'
        - '[Message] You died by mystical powers.'
   Welcome:
        - '[Broadcast] &a&l%player% &bis new on the server!'
        - '[Title]' :
            title: '&6Welcome to our server'
            subtitle: '&3Have a great time!'